// flow-typed signature: e5b6a5c4a1add42cf3b212c722562184
// flow-typed version: <<STUB>>/braintree-web-drop-in_v1.15.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'braintree-web-drop-in'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'braintree-web-drop-in' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'braintree-web-drop-in/constants' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/dist/browser/dropin' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/dropin-model' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/dropin' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/lib/add-selection-event-handler' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/lib/analytics' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/lib/assign' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/lib/browser-detection' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/lib/create-from-script-tag' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/lib/data-collector' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/lib/deferred' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/lib/dropin-error' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/lib/enumerate' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/lib/event-emitter' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/lib/find-parent-form' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/lib/is-guest-checkout' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/lib/is-https' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/lib/is-utf-8' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/lib/kebab-case-to-camel-case' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/lib/polyfill' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/lib/promise' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/lib/sanitize-html' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/lib/supports-flexbox' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/lib/three-d-secure' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/lib/transition-helper' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/lib/uuid' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/da_DK' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/de_DE' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/en_AU' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/en_GB' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/en_US' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/es_ES' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/fr_CA' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/fr_FR' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/id_ID' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/index' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/it_IT' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/ja_JP' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/ko_KR' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/nl_NL' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/no_NO' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/pl_PL' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/pt_BR' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/pt_PT' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/ru_RU' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/sv_SE' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/th_TH' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/zh_CN' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/zh_HK' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/translations/zh_TW' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/views/base-view' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/views/delete-confirmation-view' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/views/main-view' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/views/payment-method-view' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/views/payment-methods-view' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/views/payment-options-view' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/views/payment-sheet-views/apple-pay-view' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/views/payment-sheet-views/base-paypal-view' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/views/payment-sheet-views/card-view' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/views/payment-sheet-views/google-pay-view' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/views/payment-sheet-views/index' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/views/payment-sheet-views/paypal-credit-view' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/views/payment-sheet-views/paypal-view' {
  declare module.exports: any;
}

declare module 'braintree-web-drop-in/views/payment-sheet-views/venmo-view' {
  declare module.exports: any;
}

// Filename aliases
declare module 'braintree-web-drop-in/constants.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/constants'>;
}
declare module 'braintree-web-drop-in/dist/browser/dropin.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/dist/browser/dropin'>;
}
declare module 'braintree-web-drop-in/dropin-model.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/dropin-model'>;
}
declare module 'braintree-web-drop-in/dropin.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/dropin'>;
}
declare module 'braintree-web-drop-in/index' {
  declare module.exports: $Exports<'braintree-web-drop-in'>;
}
declare module 'braintree-web-drop-in/index.js' {
  declare module.exports: $Exports<'braintree-web-drop-in'>;
}
declare module 'braintree-web-drop-in/lib/add-selection-event-handler.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/lib/add-selection-event-handler'>;
}
declare module 'braintree-web-drop-in/lib/analytics.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/lib/analytics'>;
}
declare module 'braintree-web-drop-in/lib/assign.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/lib/assign'>;
}
declare module 'braintree-web-drop-in/lib/browser-detection.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/lib/browser-detection'>;
}
declare module 'braintree-web-drop-in/lib/create-from-script-tag.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/lib/create-from-script-tag'>;
}
declare module 'braintree-web-drop-in/lib/data-collector.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/lib/data-collector'>;
}
declare module 'braintree-web-drop-in/lib/deferred.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/lib/deferred'>;
}
declare module 'braintree-web-drop-in/lib/dropin-error.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/lib/dropin-error'>;
}
declare module 'braintree-web-drop-in/lib/enumerate.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/lib/enumerate'>;
}
declare module 'braintree-web-drop-in/lib/event-emitter.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/lib/event-emitter'>;
}
declare module 'braintree-web-drop-in/lib/find-parent-form.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/lib/find-parent-form'>;
}
declare module 'braintree-web-drop-in/lib/is-guest-checkout.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/lib/is-guest-checkout'>;
}
declare module 'braintree-web-drop-in/lib/is-https.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/lib/is-https'>;
}
declare module 'braintree-web-drop-in/lib/is-utf-8.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/lib/is-utf-8'>;
}
declare module 'braintree-web-drop-in/lib/kebab-case-to-camel-case.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/lib/kebab-case-to-camel-case'>;
}
declare module 'braintree-web-drop-in/lib/polyfill.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/lib/polyfill'>;
}
declare module 'braintree-web-drop-in/lib/promise.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/lib/promise'>;
}
declare module 'braintree-web-drop-in/lib/sanitize-html.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/lib/sanitize-html'>;
}
declare module 'braintree-web-drop-in/lib/supports-flexbox.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/lib/supports-flexbox'>;
}
declare module 'braintree-web-drop-in/lib/three-d-secure.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/lib/three-d-secure'>;
}
declare module 'braintree-web-drop-in/lib/transition-helper.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/lib/transition-helper'>;
}
declare module 'braintree-web-drop-in/lib/uuid.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/lib/uuid'>;
}
declare module 'braintree-web-drop-in/translations/da_DK.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/da_DK'>;
}
declare module 'braintree-web-drop-in/translations/de_DE.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/de_DE'>;
}
declare module 'braintree-web-drop-in/translations/en_AU.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/en_AU'>;
}
declare module 'braintree-web-drop-in/translations/en_GB.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/en_GB'>;
}
declare module 'braintree-web-drop-in/translations/en_US.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/en_US'>;
}
declare module 'braintree-web-drop-in/translations/es_ES.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/es_ES'>;
}
declare module 'braintree-web-drop-in/translations/fr_CA.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/fr_CA'>;
}
declare module 'braintree-web-drop-in/translations/fr_FR.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/fr_FR'>;
}
declare module 'braintree-web-drop-in/translations/id_ID.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/id_ID'>;
}
declare module 'braintree-web-drop-in/translations/index.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/index'>;
}
declare module 'braintree-web-drop-in/translations/it_IT.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/it_IT'>;
}
declare module 'braintree-web-drop-in/translations/ja_JP.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/ja_JP'>;
}
declare module 'braintree-web-drop-in/translations/ko_KR.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/ko_KR'>;
}
declare module 'braintree-web-drop-in/translations/nl_NL.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/nl_NL'>;
}
declare module 'braintree-web-drop-in/translations/no_NO.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/no_NO'>;
}
declare module 'braintree-web-drop-in/translations/pl_PL.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/pl_PL'>;
}
declare module 'braintree-web-drop-in/translations/pt_BR.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/pt_BR'>;
}
declare module 'braintree-web-drop-in/translations/pt_PT.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/pt_PT'>;
}
declare module 'braintree-web-drop-in/translations/ru_RU.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/ru_RU'>;
}
declare module 'braintree-web-drop-in/translations/sv_SE.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/sv_SE'>;
}
declare module 'braintree-web-drop-in/translations/th_TH.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/th_TH'>;
}
declare module 'braintree-web-drop-in/translations/zh_CN.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/zh_CN'>;
}
declare module 'braintree-web-drop-in/translations/zh_HK.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/zh_HK'>;
}
declare module 'braintree-web-drop-in/translations/zh_TW.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/translations/zh_TW'>;
}
declare module 'braintree-web-drop-in/views/base-view.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/views/base-view'>;
}
declare module 'braintree-web-drop-in/views/delete-confirmation-view.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/views/delete-confirmation-view'>;
}
declare module 'braintree-web-drop-in/views/main-view.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/views/main-view'>;
}
declare module 'braintree-web-drop-in/views/payment-method-view.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/views/payment-method-view'>;
}
declare module 'braintree-web-drop-in/views/payment-methods-view.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/views/payment-methods-view'>;
}
declare module 'braintree-web-drop-in/views/payment-options-view.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/views/payment-options-view'>;
}
declare module 'braintree-web-drop-in/views/payment-sheet-views/apple-pay-view.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/views/payment-sheet-views/apple-pay-view'>;
}
declare module 'braintree-web-drop-in/views/payment-sheet-views/base-paypal-view.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/views/payment-sheet-views/base-paypal-view'>;
}
declare module 'braintree-web-drop-in/views/payment-sheet-views/card-view.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/views/payment-sheet-views/card-view'>;
}
declare module 'braintree-web-drop-in/views/payment-sheet-views/google-pay-view.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/views/payment-sheet-views/google-pay-view'>;
}
declare module 'braintree-web-drop-in/views/payment-sheet-views/index.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/views/payment-sheet-views/index'>;
}
declare module 'braintree-web-drop-in/views/payment-sheet-views/paypal-credit-view.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/views/payment-sheet-views/paypal-credit-view'>;
}
declare module 'braintree-web-drop-in/views/payment-sheet-views/paypal-view.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/views/payment-sheet-views/paypal-view'>;
}
declare module 'braintree-web-drop-in/views/payment-sheet-views/venmo-view.js' {
  declare module.exports: $Exports<'braintree-web-drop-in/views/payment-sheet-views/venmo-view'>;
}
